### ISSUE TITLE
Product Card Alignment 

### ISSUE THREAD

**Issue by tusharnankani** [HarshKapadia2/hps-gems#3]
Hi, just came across this again, couldn't fix it as wanted, but in my opinion, this looks kinda better than the current behavior. 

https://user-images.githubusercontent.com/61280281/103140378-d6452480-470b-11eb-87bc-2e9081876f12.mp4

Have used flexbox though.

![image](https://user-images.githubusercontent.com/61280281/103140350-93834c80-470b-11eb-82d0-581766d176a5.png)

I know this isn't that big of an issue to be dealt with, but I was really curious about making how can we do it, let me know your thoughts.

**Comment by HarshKapadia2** [comment]
I'm not sure the centering looks that good. The starting of all items from one level gives a uniform look. This is also why I am considering not to use the [Masonry layout](https://drafts.csswg.org/css-grid-3/) even when it becomes supported. Not sure though. Let's see.
What do you think?

**Comment by tusharnankani** [comment]
> The starting of all items from one level gives a uniform look. 

It is more like a personal preference.

> I'm not sure the centering looks that good. 

I think this looks better, the opinion would vary.

> What do you think?

Again, as I mentioned: it isn't that big of an issue to be dealt with, but I was really curious about making how can we do it.
